CREATE TABLE IF NOT EXISTS mcaptcha_config (
	config_id SERIAL PRIMARY KEY NOT NULL,
	domain_name VARCHAR(100) NOT NULL references mcaptcha_domains(name) ON DELETE CASCADE,
	key VARCHAR(100) NOT NULL UNIQUE,
	name VARCHAR(100) NOT NULL UNIQUE,
	duration INTEGER NOT NULL DEFAULT 30
);
